apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../cluster-components-flux
- ../../cluster-components-flux/optional/charlie.yaml

labels:
  - pairs:
      gwcp.guidewire.com/dept: '2'
      atmos-cluster: badger
      atmos.guidewire.com/cluster-component: "true"

patches:
  - target:
      name: .*
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/podAnnotations
        value:
          test: "1"
  - target:
      name: alpha
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
      - op: replace
        path: /metadata/labels/gwcp.guidewire.com~1dept
        value: 2
      - op: add
        path: /spec/postRenderers/0/kustomize/patches/-
        value:
          patch: |-
            - op: replace
              path: /metadata/labels/gwcp.guidewire.com~1dept
              value: '2'
          target:
            name: .*
            kind: .*
      - op: add
        path: /spec/postRenderers/0/kustomize/patches/-
        value:
          patch: |-
            - op: replace
              path: /spec/template/metadata/labels/gwcp.guidewire.com~1dept
              value: '2'
          target:
            name: .*
            kind: Deployment
  - target:
      name: bravo
      kind: HelmRelease
    patch: |
      - op: replace
        path: /spec/values/replicaCount
        value: 2
