---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: cluster-components-flux-helm
  namespace: flux-system
spec:
  interval: 1m
  ref:
    # branch: main
    branch: test-dependson
    # tag: v0.1.0
  url: https://github.com/merusso/cluster-components-flux-helm.git
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: components
  namespace: flux-system
spec:
  chart:
    spec:
      chart: .
      reconcileStrategy: Revision
      sourceRef:
        kind: GitRepository
        name: cluster-components-flux-helm
  interval: 10m0s
  values:
    departmentCode: 2
    alpha:
      values:
        podAnnotations:
          test: "1"
        replicaCount: 2
    bravo:
      values:
        podAnnotations:
          test: "1"
        replicaCount: 2
    charlie:
      enabled: true
      values:
        podAnnotations:
          test: "1"
        replicaCount: 2
